### ISSUE TITLE
no start line

### ISSUE THREAD

**Issue by richenlin** [spacewander/lua-resty-rsa#1]
定义pubkey，resty_rsa:new(RSA_PUBLIC_KEY, true);

返回错误  no start line

**Comment by richenlin** [comment]
local RSA_PUBLIC_KEY = io.input("/usr/local/openresty/nginx/conf/rsa_user_public_key.pem");
local pub, err = resty_rsa:new(RSA_PUBLIC_KEY);

这样写仍然报错 no start line ，救命啊

**Comment by doujiang24** [comment]
rsa 的key 有多种格式，目前用以下的生成方式是没有问题的

```
openssl genrsa -out private.pem 1024
openssl rsa -in private.pem -RSAPublicKey_out -out public.pem
```

当然，应该只是读取格式不一样，如果在其他库里（比如php里用另外的格式加密内容），在这边一样可以解开的，这个没有做过测试，如有需要你可以测试以下 :）

**Comment by doujiang24** [comment]
rsa的参考文档：https://www.openssl.org/docs/apps/rsa.html

**Comment by richenlin** [comment]
非常感谢回复，已经找到原因了，就是因为pubkey的格式问题，PEM_read_RSA_PUBKEY()函数和PEM_read_RSAPublicKEY()读取公钥格式不同，看您的源码，是用的PEM_read_RSAPublicKEY()

是否考虑兼容下

**Comment by doujiang24** [comment]
这个可以有 :) 也欢迎贡献补丁 :)
