### ISSUE TITLE
错误: data greater than mod len

### ISSUE THREAD

**Issue by coder-zhuyu** [spacewander/lua-resty-rsa#10]
我用这个库去解密文出现错误信息：data greater than mod len

**Comment by coder-zhuyu** [comment]
试了下分组解密就可以了

**Comment by MichaelDick1776** [comment]
I also encountered this error...
What is the specific solution?

**Comment by MichaelDick1776** [comment]
Solved.
This is my way. Hope can help others.
Before decrypting, decode with base64.
```
local decode_b64 = ngx.decode_base64(encrypted)
local res, err = priv:decrypt(encode_b64)
```

**Comment by jingquanxie** [comment]
> 我用这个库去解密文出现错误信息：data greater than mod len

你是怎么使用lua  去分组解密的呢？

**Comment by ytlm** [comment]
> 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/11896584/170513494-0b21c3a4-577b-47b7-87f7-64c2e270de98.png">
我也遇到了这个 *data greater than mod len* 错误，我的使用方式就是上面截图那样
