### ISSUE TITLE
签名结果跟其他语言的不同啊？

### ISSUE THREAD

**Issue by x6587305** [spacewander/lua-resty-rsa#11]
这个例子是sha1withrsa 的签名嘛？ 我签名结果跟其他语言不同啊。java 和 oc 签名结果是一致的。确定证书没问题。

**Comment by spacewander** [comment]
可以把用 `lua-resty-rsa` 签名的代码和用 java 签名的代码发出来看看吗？

**Comment by x6587305** [comment]
可以加qq说吗 261681926

在 2016-12-23 11:13:02，"罗泽轩" <notifications@github.com> 写道：


可以把用 lua-resty-rsa 签名的代码和用 java 签名的代码发出来看看吗？

**Comment by x6587305** [comment]
lua-----------------------
local algorithm = "SHA"
local priv, err = resty_rsa:new({ 
    private_key = RSA_PRIV_KEY, algorithm = algorithm })
if not priv then
    ngx.say("new rsa err: ", err)
    return
end

local str = "1"
local sig, err = priv:sign(str)
if not sig then
    ngx.say("failed to sign:", err)
    return
end
---------------------------
	/**
	 * sha1WithRsa 加签
	 * 
	 */
	public static String rsaSign(String content, String privateKey,
			String charset) throws Exception {
		try {
			PrivateKey priKey = getPrivateKeyFromPKCS8(Constants.SIGN_TYPE_RSA,
					new ByteArrayInputStream(privateKey.getBytes()));

			java.security.Signature signature = java.security.Signature
					.getInstance(Constants.SIGN_ALGORITHMS);

			signature.initSign(priKey);

			if (StringUtils.isEmpty(charset)) {
				signature.update(content.getBytes());
			} else {
				signature.update(content.getBytes(charset));
			}

			byte[] signed = signature.sign();
			String sign =  new String(Base64.encode(signed));
			return sign;
		} catch (InvalidKeySpecException ie) {
			throw new Exception("RSA私钥格式不正确，请检查是否正确配置了PKCS8格式的私钥", ie);
		} catch (Exception e) {
			throw new Exception("RSAcontent = " + content + "; charset = " + charset, e);
		}

	}
	public static PrivateKey getPrivateKeyFromPKCS8(String algorithm,
			InputStream ins) throws Exception {
		if (ins == null || StringUtils.isEmpty(algorithm)) {
			return null;
		}

		KeyFactory keyFactory = KeyFactory.getInstance(algorithm);

		byte[] encodedKey = StreamUtil.readText(ins).getBytes();

		encodedKey = Base64.decode(encodedKey);

		return keyFactory.generatePrivate(new PKCS8EncodedKeySpec(encodedKey));
	}

	public String getStringForSign(HttpServletRequest request) throws Exception{
		String singCOntent = "1";
		String sign = SecurityUtils.rsaSign(singCOntent, privateKey, null);
		System.out.println(sign);
		boolean isTrue =  SecurityUtils.rsaCheckContent(singCOntent, sign, publicKey, null);
		System.out.println(isTrue);
		return  sign;
	}
=================
我写死的 字符串 看下签名的。 然后 能加下我qq 261681926 指导一下我嘛大神？

**Comment by spacewander** [comment]
会不会是跟 #9 差不多的问题？
你试下用 openssl 把私钥转成 pkcs1 的格式，再试试？目前 `lua-resty-rsa` 还不支持 pkcs8 的格式。

**Comment by x6587305** [comment]
不会 证书我确定没问题。应为java用的是pkcs8 iOS用的是pkcs1生成的p12。而且如果弄错了 程序会报错。我现在在只用rsa加密解密的话。java加密 lua解密是可以的。就是签名就不对了


发自网易邮箱大师
在2016年12月23日 13:46，罗泽轩 写道:

会不会是跟 #9 差不多的问题？
你试下用 openssl 把私钥转成 pkcs1 的格式，再试试？目前 lua-resty-rsa 还不支持 pkcs8 的格式。

**Comment by spacewander** [comment]
```java
PrivateKey priKey = getPrivateKeyFromPKCS8(Constants.SIGN_TYPE_RSA,
				new ByteArrayInputStream(privateKey.getBytes()));

java.security.Signature signature = java.security.Signature
				.getInstance(Constants.SIGN_ALGORITHMS);
```
这里 `Constants.SIGN_TYPE_RSA` 和 `Constants.SIGN_ALGORITHMS` 对应的值是多少？貌似不属于 Java 标准库的内容？

**Comment by x6587305** [comment]
public final static String SIGN_TYPE_RSA 	    = "RSA";
 public static final String SIGN_ALGORITHMS                = "SHA1WithRSA";
大神 要不加我qq吧 261681926

**Comment by spacewander** [comment]
你试试，把 `local algorithm = "SHA"` 这一行改成 `local algorithm = "SHA1"`？

**Comment by x6587305** [comment]
貌似的确是这个。。。我以为 SHA 就是 SHA1 压根没想到会是这里出了问题。谢谢大神。。那么SHA 跟 SHA1的区别是什么啊 大神。

**Comment by spacewander** [comment]
SHA => SHA0
`lua-resty-rsa` 目前没有说明签名算法支持的文档，我打算周末加上。

如果没别的问题，这个 issue 我就关闭了哦。有问题再重新打开吧。

**Comment by x6587305** [comment]
好的没别的问题了。谢谢您了
