### ISSUE TITLE
通过opm get doujiang24/lua-resty-rsa安装的不是master版本？

### ISSUE THREAD

**Issue by wuyachao** [spacewander/lua-resty-rsa#16]
opm安装的版本里面没有generate_rsa_keys方法，请问使用哪一个版本好呢？

**Comment by wuyachao** [comment]
请问大佬，为什么我生成的公钥里面最后面有奇怪的符号呢？
```
  -----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAwqtmlQEk0epDWVHH2cKKLDF+fc3rSd5pDejVP+pddoIkmBd18iuL
yHypQhmKeI0v9+hZTOXGzuL3aWr3EuV7dQdYxkw8fVJw9Mol7hVaAJva8wLB1sYY
JUcKC3NRZWuZVaa/TFgl09ychp5fnyl5iofeSm8gtTiQyfIF9aSvMaJBgDM7TthY
TTbz9rwmdohmexqA9YGWS+z/UIXUJ/IjkGju+BCaxPpUTeyipyfGj7zNrfT306L6
bCslG29VApPd0YxTHQyrtNhLw8T3IokEEXXMrzOJbT2UCsVfyREpazjg9dSuKmVF
/xPGa4F242n5D/2pTLnwdGEa7Voh5bGC5wIDAQAB
-----END RSA PUBLIC KEY-----
a);
tyÓ^A
~       
```

**Comment by spacewander** [comment]
关于第一个问题，我没有权限更新 opm 上面的 doujiang24/lua-resty-rsa。
这个需要有劳 @doujiang24 帮忙更新下。

关于第二个问题，这个“奇怪的符号”是必现的吗？如果不输出到终端里，而是写入到文件中，还会出现这种特殊字符不？

**Comment by wuyachao** [comment]
@spacewander 是的，代码就是简单的ngx.say()输出
```
local rsa_public_key, rsa_priv_key, err = resty_rsa:generate_rsa_keys(2048)
local resty_rsa = require "resty.rsa"
ngx.say(rsa_public_key)
ngx.say(rsa_priv_key)
```
代码放在content_by_lua_file中，请求然后chrome自动下载文件一个文件，无论vim打开还是sublime打开中间都有这个怪怪的符号，不知道是不是我使用方式不对？
编码格式使用的也是utf-8打开的

**Comment by wuyachao** [comment]
浏览器打开的时候中间是nt PEM#这个东西

**Comment by spacewander** [comment]
> 浏览器打开的时候中间是nt PEM#这个东西

呃，从上面的描述看，打开的文本里是没有这个东西的。请问“中间”是指哪里的中间？

我尝试用 chrome 去复现你的问题，但是没法重现。

随便一提，如果 Content-Type 是 text/plain 的话（这个是 Nginx defualt_type 的默认设置），chrome 是直接展示在页面，而不会自动下载的。不知道你的 Content-Type 有没有设置成别的什么？

**Comment by wuyachao** [comment]
@spacewander 请问，因为是和node联合调试，请问这个decrypt解密，接受的什么格式的，binary，ascii，还是string，联调不通过，求助

**Comment by spacewander** [comment]
string.
你可以把 node 发过来的内容，跟 encrypt 之后生成内容比对下，看看有没可能缺了点东西

2017-08-14 18:00 GMT+08:00 wuyachao <notifications@github.com>:

**Comment by wuyachao** [comment]
@spacewander  刚才忘记了，type打印出来是string，我再好好看看哪里不一样。谢谢大佬

**Comment by wuyachao** [comment]
@spacewander  已经解决了，原来直接传二进制可能出问题了，node那边加密后转化为base64,这边decode然后解密，但是效率和readme上面写的差距查了5倍，我decode_base64循坏10万次，耗时0.12秒，所以不知道是哪里出问题导致这么慢.
ttt.lua
```
local priv, err = resty_rsa:new({ private_key = rsa_priv_key })
if not priv then
  ngx.say("new rsa err: ", err)
  return
end

local encrypted = [[
BLSFh9O6VPO6JeQlTqXa2uz6BqNjOLhUleBUCX12aBkZEE6bZZCeot6i4UgAOfw+hRirLYD3sP7oOrMwhbNAVm/SoZlruI7PTUt9mAiagK2dXeRPzobxAgE3ekva3IJl12xbpsNP8YMdT8fL7CxHWlynv7bifda6FGZGWsiltuMP6VTXQywluiuBMgvFnxjFa1M5PUDEQIRxtVj2YUms7sqAeX+dSG8iwT/jPT26joW3uHdzjaonXXMuYYnQHqsqpT+9/eXCFjslWNnI7eGh5dXoM4ab9QhwhnucPhn2iFMWTnb+TGyhSzTg6XbyU1pD98RCGohJhUeHswjzfx/Lkg==
]]

for i = 1, 50000 do
  local decrypted = priv:decrypt(ngx.decode_base64(encrypted))
end
ngx.say(decrypted)
```
然后运行`time /usr/local/openresty/bin/resty ttt.lua`
```
real	1m11.071s
user	1m8.994s
sys	0m0.095s
```

**Comment by spacewander** [comment]
注意到 README 上 key 的长度吗？:)
rsa 的效率很大程度上取决于 key 的长度。Benchmark 里面的 key 只有 1024 字节（这种长度的 key
并不安全，已经被淘汰了），而实际用到的 key 都是 2048 字节甚至更长。

2017-08-15 11:22 GMT+08:00 wuyachao <notifications@github.com>:

**Comment by wuyachao** [comment]
@spacewander  好吧，用的2048字节，感觉差距有点大。非常谢谢大佬
