### ISSUE TITLE
PATCH: add PKCS#8 key generation

### ISSUE THREAD

**Issue by tarkin000** [spacewander/lua-resty-rsa#18]
patch:
[rsa.lua.patch](https://gist.github.com/tarkin000/d8524946c2b0793ab10accb41a37087b#file-rsa-lua-patch)

API update:
```lua 
  rsa:generate_rsa_keys(bits,pkcs8)
```

test:
  ```lua
local rsa = require("resty.rsa")
local pub, prv, err = rsa:generate_rsa_keys(512, true)
print(pub)
print(prv)
print(err)
```

**Comment by spacewander** [comment]
@tarkin000 
https://gist.github.com/tarkin000/d8524946c2b0793ab10accb41a37087b#file-rsa-lua-patch-L66
You should use `pkcs8` directly instead of `do8`. The result of `type(nil)` is `"nil"` but not `nil`.

Moreover, the code should be indented with space, with trailing whitespace removed. [luacheck](http://luacheck.readthedocs.io/) grumbles about this.

**Comment by tarkin000** [comment]
I will fix and resubmit

**Comment by tarkin000** [comment]
fixed whitespace issues (no tab chars, 4 space indent)
pkcs8 is used directly, now must be boolean AND true
[https://gist.github.com/tarkin000/d8524946c2b0793ab10accb41a37087b#file-rsa-lua-patch](https://gist.github.com/tarkin000/d8524946c2b0793ab10accb41a37087b#file-rsa-lua-patch)

When I use resty cli, I sometimes get garbage printed after the keys
 a newline + 1-4 random chars, do you?

```
-----BEGIN RSA PUBLIC KEY-----
MEgCQQDDkojZSa395IHJAQB1KlRulY8lTDqVnO7KKwPRQ4a05v4dxiqz40gxrOpP
UxacY0HAtlN4BO3JknrCvyRzHua5AgMBAAE=
-----END RSA PUBLIC KEY-----
AA
```

**Comment by spacewander** [comment]
@tarkin000 
Not sure... I will investigate it.

**Comment by spacewander** [comment]
@tarkin000 
Your patch has been applied as https://github.com/doujiang24/lua-resty-rsa/commit/943e1c59974a7bbf5eb142d7e24c52055b8db71e. Thanks for your contribution!

**Comment by tarkin000** [comment]
Thanks for the great project!
