### ISSUE TITLE
最新的代码可以写个私钥加密，公钥解密吗？

### ISSUE THREAD

**Issue by xiaoxin1** [spacewander/lua-resty-rsa#20]
我尝试按照之前Issue里面的代码改了，but failed

**Comment by spacewander** [comment]
没有添加这项功能的计划，理由我已经写在 https://github.com/doujiang24/lua-resty-rsa/issues/6 了。

> 但是我没有把它放入 rsa 库的打算。因为私钥加密/公钥解密本身是有违最佳实践的，相对来说不够安全。参见这个 SO 回答：
> https://crypto.stackexchange.com/a/2125

**Comment by xiaoxin1** [comment]
好的，我模仿这个代码终于改成功了。这个不够安全，但是目前需要这样做，感谢你们的项目。
