### ISSUE TITLE
OpenSSL_add_all_digests这种函数不应重复初始化

### ISSUE THREAD

**Issue by houfengjiejie** [spacewander/lua-resty-rsa#21]
**OpenSSL_add_all_digests这种函数只初始化一次就可以了吧 ，应该在require module的时候显示调用一下，而不是 在每次建立实例的时候调用，因为重复调用相当于空操作**

**Comment by spacewander** [comment]
@houfengjiejie 
多谢指正。
我重新看了这一块的代码，由于 Nginx 会在启动时调用 `ngx_ssl_init`，这个函数调用了 `OpenSSL_add_all_algorithms`，间接会调用到 `OpenSSL_add_all_digests`。
所以我打算更加激进一点，直接从 lua-resty-rsa 移除该函数。你看这样如何？

**Comment by houfengjiejie** [comment]
目前nginx确实是这样实现的，只要在configure的时候加了 openssl就会调用OpenSSL_add_all_digests，但是设计模式的原则是最小依赖，万一有一天nginx不调用了，那自己的库又被坑了 ，我感觉在模块被 require的时候调用一次不会有啥影响

**Comment by spacewander** [comment]
嗯，调用多几次影响也不大。不过还有个版本兼容的问题。
其实 OpenSSL 自 1.1.0 之后就移除了  `OpenSSL_add_all_digests`。`ngx_ssl_init` 里面也有根据 OpenSSL 版本决定是否需要调用 `OpenSSL_add_all_algorithms`。未来要想支持 OpenSSL 1.1.0，我们这边也会移除掉这个函数。所以干脆先从现在开始移除好了。

**Comment by houfengjiejie** [comment]
如果 openssl把OpenSSL_add_all_digests去了 ，那要吐槽下 openssl了，向下 兼容做的真差，

**Comment by spacewander** [comment]
@houfengjiejie 
你这话说到我的心坎上了。OpenSSL 一向以糟糕的文档和糟糕的兼容性著称。

**Comment by houfengjiejie** [comment]
问个额外的问题，可不可以在init_by_lua初始化一个全局的rsa实例对象，其他请求直接通过这个实例对象加解密

**Comment by spacewander** [comment]
个人认为不会有问题。因为 Nginx 是单线程的，而且 rsa 实例对象在操作中只是共享了 EVP_PKEY_CTX 和 buffer。实际操作中
CTX 应该是只读的，而 buffer 每次都会填充。
当然我不是 OpenSSL 专家，另外 rsa 操作的主要耗时在算法上，对象初始化的耗时不大。

2017-12-15 14:38 GMT+08:00 houfengjiejie <notifications@github.com>:

**Comment by spacewander** [comment]
如果不放心，可以结合 Valgrind 或者 clang asan 压测看看？

在 2017年12月15日 下午3:02，Zexuan Luo <spacewanderlzx@gmail.com>写道：

**Comment by houfengjiejie** [comment]
其实是这个问题引出了我对openresty支持单实例（只初始化一个全局对象，供进程内所有请求使用，而不是每个请求都去创建一个实例，这样后果是都会调用new函数）的疑惑，但是目前来看很少有这么用的，openrsty得官方文档也只是介绍说在init_by_lua中require一些库之类的，不知道这样做会有啥弊端

而且openresty目前的实现也是只允许在init_by_lua修改全局表，其他阶段都是继承全局表，但是不允许写入全局表（c实现了）

**Comment by spacewander** [comment]
这个就跟 lua-resty-rsa 无关了。rsa 实例只涉及到两方面的内存管理：OpenSSL 和 Lua GC，跟 Lua 全局表没什么关系。

在 2017年12月15日 下午3:09，houfengjiejie <notifications@github.com>写道：

**Comment by houfengjiejie** [comment]
是的，我是说问个关于全局单实例额外问题

**Comment by spacewander** [comment]
这个就取决于具体实现了。不同的库内部实现不一样，不一定都可以直接设置成单实例。

2017-12-15 15:40 GMT+08:00 houfengjiejie <notifications@github.com>:

**Comment by spacewander** [comment]
已经在最新的提交中移除了 OpenSSL_add_all_digests
https://github.com/doujiang24/lua-resty-rsa/commit/021640e546000cac3df8edc59c3a9535955712a6
