### ISSUE TITLE
最后一个\n符后面有时候会多出一些特殊字符

### ISSUE THREAD

**Issue by yiyi910** [spacewander/lua-resty-rsa#24]
![image](https://user-images.githubusercontent.com/8814700/39394033-40579e22-4aff-11e8-8ece-8dc6b327463a.png)
你好，generate_rsa_keys(1024) 产生的公钥，最后一个\n符后面有时候会多出一些特殊字符，截图是我用cjson.encode转成json数据的

**Comment by spacewander** [comment]
@yiyi910 
这个我记得在 https://github.com/doujiang24/lua-resty-rsa/commit/876a76e717ba169ef987cd3a23717ad2e7e90b61 修复过类似的问题。
你从 master 分支上安装下，看看还有没有同样的问题。
如果依旧能复现，麻烦提供一个最小的可供重现的例子。

**Comment by spacewander** [comment]
Consider solved.
