### ISSUE TITLE
push current version to opm

### ISSUE THREAD

**Issue by c64bob** [spacewander/lua-resty-rsa#27]
Could you please push the current version of lua-resty-rsa to opm? The one I just installed using opm get still has the line `C.OpenSSL_add_all_digests()` in it, which you have since removed from your git repository.

**Comment by spacewander** [comment]
@doujiang24 
Would you have spare time to release a new version of lua-resty-rsa to the opm?

**Comment by spacewander** [comment]
@c64bob 
After discussed with @doujiang24, he decided to transfer the repo to me.
So now you could install the latest `lua-resty-rsa` with `opm install spacewander/lua-resty-rsa`.

**Comment by c64bob** [comment]
Thank you for the quick fix!
