### ISSUE TITLE
公钥BEGIN LINE关键字错误

### ISSUE THREAD

**Issue by imilli** [spacewander/lua-resty-rsa#28]
接口中输入的公钥抬头为：
-----BEGIN RSA PUBLIC KEY-----
然而openssl生成的公钥抬头为：
-----BEGIN PUBLIC KEY-----
没有RSA关键字，只有私钥里才有，希望更正一下。

**Comment by spacewander** [comment]
@imilli 
这两种公钥是两种格式不同的公钥。`-----BEGIN PUBLIC KEY-----` 开头的是 `PKCS#8` 格式的。
你可以看下这个测试用例：https://github.com/spacewander/lua-resty-rsa/blob/master/t/rsa.t#L745

**Comment by spacewander** [comment]
需要在 `new` 的时候指定下 `key_type` 参数，相关文档：https://github.com/spacewander/lua-resty-rsa#new

**Comment by spacewander** [comment]
Consider solved.
