### ISSUE TITLE
当前库无法用私钥解密其他js库加密的密文

### ISSUE THREAD

**Issue by wuzuhong** [spacewander/lua-resty-rsa#29]
使用sencrypt.js公钥加密后，再使用当前库来私钥解密，解不出来，该怎么解决？

**Comment by spacewander** [comment]
@wuzuhong 
请提供一个可以直接运行的、最小的可重现用例，否则没办法知道代码是怎么写的。最好能提供一个 package.json 可以直接安装特定版本的 sencrypt.js。另外你用的 lua-resty-rsa 是哪个版本的？

**Comment by wuzuhong** [comment]
现在已经解决了，开始是因为没有进行base64解码

**Comment by wuzuhong** [comment]
> @wuzuhong
> 请提供一个可以直接运行的、最小的可重现用例，否则没办法知道代码是怎么写的。最好能提供一个 package.json 可以直接安装特定版本的 sencrypt.js。另外你用的 lua-resty-rsa 是哪个版本的？

现在已经解决了，开始是因为没有进行base64解码

**Comment by spacewander** [comment]
明白。
