### ISSUE TITLE
兄弟能不能加一下签名和验签方法

### ISSUE THREAD

**Issue by wkii** [spacewander/lua-resty-rsa#3]
这里有一位朋友已经添加上了，不过也没有给用例。签名中他默认使用SHA256，而我还想可选SHA1
还有，用其它语言，同一个私钥，签名结果不一致。
您能不能完善一下您的类，加上签名和验签方法？非常感谢。

**Comment by doujiang24** [comment]
这个可以有，只是最近有点忙，乐观估计下周可以抽时间搞一个出来

**Comment by wkii** [comment]
太棒了。先谢谢你。我就静候佳音啦。
第二个小问题，之前一位朋友也反馈过，生成公钥要加-RSAPublicKey_out 参数。而一些版本的openssl是不支持这个参数的。比如mac上用brew安装的openssl。
如果能支持openssl rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem这种形式生成的公钥就更好了。当然，这个用那一种倒是都可以接受，不紧急不重要。

**Comment by doujiang24** [comment]
@wkii 不好意思哈，最近太忙了点，拖了这么久，终于挤时间完成了 sign/verify 这组 api，有空看看满意不，哈哈

**Comment by uudiin** [comment]
你好，有木有生成动态生成公钥及私钥的api

**Comment by hylun** [comment]
用openssl rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem生成的公钥解析失败，为什么？
用在线工具http://web.chacuo.net/netrsakeypair 生成的RSA密钥对也不能用

**Comment by 18099538715** [comment]
java生成的私钥怎么直接使用？总数报 bad base64 decode，在windows系统上可以使用，到linux上又不行 了

**Comment by spacewander** [comment]
@18099538715 
`bad base64 decode` 表示私钥格式有问题。你可以比较下 Linux 上的私钥跟 Windows 上的是否完全相同。

**Comment by spacewander** [comment]
签名和验签的方法两年前已经添加了。考虑到原来的主题已经有相当长的一段时间没有回复，暂且先把本 issue 关闭掉。如果有相关的问题再另开一个吧。
