### ISSUE TITLE
failed to encrypt client secret: wrong tag: nested asn1 error: Type=RSA: ASN1 lib

### ISSUE THREAD

**Issue by JuPretty** [spacewander/lua-resty-rsa#33]
您好，我在RSA加密时遇到问题，failed to encrypt client secret: wrong tag: nested asn1 error: Type=RSA: ASN1 lib。实在没有找到问题所在。
OpenSSL 1.0.1e-fips

**Comment by spacewander** [comment]
可以提供一个最小可重现的用例吗？以及 lua-resty-rsa 的版本号。

**Comment by spacewander** [comment]
有最小可重现用例的时候再 reopen 这个 issue 吧。
