### ISSUE TITLE
resty_rsa:new({public_key = rsa_pubilc_key, algorithm = 'SHA1' })中公钥格式问题无报错

### ISSUE THREAD

**Issue by zcong2333** [spacewander/lua-resty-rsa#36]
resty -e '
local cjson = require("cjson")
local resty_string = require "resty.string"

local find = string.find
local sub = string.sub
local gsub = string.gsub
local resty_rsa = require "resty.rsa"
local RSA_PUBLIC_KEY = [[
-----BEGIN PUBLIC KEY-----
aa
-----END PUBLIC KEY-----
]]

local rsa_public_key,err = string.gsub(RSA_PUBLIC_KEY, "aa", "-----BEGIN PUBLIC KEY----- MIGfMA0GCSqGSIb3DQEAAQUAA4GNADCBiQKBgQC3f/TBa4c+jMjYiHJQAuW4Ay6m Y1KnIPAUeKMVdaZgeW+1f0SCpCT9g1AVhgbQ2coeoNmLsL/16xqs9QccFDvJzs7k YKcHI/STLKTvaEXFt3VTbnl+Sxq96L4bX7StBq9qS1Yo+cdzshsFQ/5rCJ2sy8pR zHPoC9+Vb0t+MrN4fQIDAQAB -----END PUBLIC KEY-----")
 ngx.say("rsa_public_key: ", rsa_public_key)
 
local pub, err = resty_rsa:new({ public_key = rsa_public_key, algorithm = 'SHA1' })
 ngx.say("new rsa err: ", err)
    if not pub then
        ngx.say("new rsa err: ", err)
    end
	 local verify, err = pub:verify("ssss", "xxxxxxxxxxx")
	  if not verify then
        ngx.say("verify err: ", err)
        return
    end
    ngx.say(verify)

' 
我使用上面的测试代码，测试后，结果只打印了
rsa_public_key: -----BEGIN PUBLIC KEY-----
-----BEGIN PUBLIC KEY----- MIGfMA0GCSqGSIb3DQEAAQUAA4GNADCBiQKBgQC3f/TBa4c+jMjYiHJQAuW4Ay6m Y1KnIPAUeKMVdaZgeW+1f0SCpCT9g1AVhgbQ2coeoNmLsL/16xqs9QccFDvJzs7k YKcHI/STLKTvaEXFt3VTbnl+Sxq96L4bX7StBq9qS1Yo+cdzshsFQ/5rCJ2sy8pR zHPoC9+Vb0t+MrN4fQIDAQAB -----END PUBLIC KEY-----
-----END PUBLIC KEY-----

公钥有问题的情况下，似乎直接退出了，而没有报错信息返回。

**Comment by spacewander** [comment]
Look like OpenSSL doesn't provide any error message with some malformed public keys. Will dive into it when I have enough free time. Thanks for your report.

**Comment by spacewander** [comment]
@zcong2333 
我追了下 OpenSSL 的内部实现，发现在 `PEM_read_bio` 里面，如果 `EVP_DecodeFinal` 没有更新传进去的长度参数，那么就不会有报错。这一块应该是 OpenSSL 实现的问题。我改了下代码，如果 OpenSSL 没有提供错误信息，那么返回一个 "internal error"。

另外，对于 `-----BEGIN PUBLIC` 开头的公钥，记得加上  `key_type = resty_rsa.KEY_TYPE.PKCS8,`，参考文档：
https://github.com/spacewander/lua-resty-rsa#new

**Comment by zcong2333** [comment]
@spacewander 
好的，多谢提醒。多问一句，我这边更新版本就可以了吧

**Comment by zcong2333** [comment]
我更新了rsa.lua.可以了。多谢
