### ISSUE TITLE
Luarocks.org reflects version 0.04 only

### ISSUE THREAD

**Issue by 27ascii** [spacewander/lua-resty-rsa#40]
lua-resty-rsa is not automatically beeing installed when adding it as dependency:
```
dependencies = {
  "lua ~> 5.1",
  "lua-resty-jwt ~> 0.2.2",
  "lua-resty-rsa >= 1.0",
}
```
Luarocks only reflects the 0.04 version if this module: https://luarocks.org/modules/p0pr0ck5/lua-resty-rsa 
Are there any plans to reference the latest version?

**Comment by spacewander** [comment]
As you may notice, this library is owned by @p0pr0ck5.
@p0pr0ck5 uploaded this library without contacting us, therefore I can't release my own one.

**Comment by 27ascii** [comment]
hmm, maybe you could request to transfer the ownership. according @hishamhm the ownership could be transfered as an administrative task https://gitter.im/luarocks/luarocks?at=5c49d3030a491251e34a8a5a

**Comment by spacewander** [comment]
@27ascii 
Could you request it for me?

**Comment by 27ascii** [comment]
Hi @hishamhm i'm try to sort out an ownership issue for the lua-resty-rsa library on behalf of the owner @spacewander.

Would it be possible to transfer the owner ship of the library https://luarocks.org/modules/p0pr0ck5/lua-resty-rsa from @p0pr0ck5 to @spacewander 

p0pr0ck5 did publish an very early version 0.04 of this repo - in the meanwhile version 1.1.0 is available, however updates haven't been uploaded to luarocks.

If you'd transfer the ownership to the repo owner new version can be uploaded.

**Comment by hishamhm** [comment]
@27ascii Done!

@spacewander, the module is now under your account, feel free to push updates:

https://luarocks.org/modules/spacewander/lua-resty-rsa

**Comment by spacewander** [comment]
@hishamhm @27ascii 
Thanks!
I will upload a new one today.

**Comment by spacewander** [comment]
Done.
