### ISSUE TITLE
支付宝开放平台开发助手 生成的公私钥对(pkcs#1)格式问题

### ISSUE THREAD

**Issue by epiphyllum** [spacewander/lua-resty-rsa#42]
lua-resty-rsa生成的 公私钥样例(pkcs#1)如下
![image](https://user-images.githubusercontent.com/8348065/122334478-630ac580-cf6c-11eb-9bf8-f0ffe123308c.png)

用支付宝工具生成的公私钥样例(pkcs#1)如下
![image](https://user-images.githubusercontent.com/8348065/122334560-82095780-cf6c-11eb-91b7-4b31c0e31f7e.png)

将支付宝私钥(pkcs#1)转成PEM格式后， 做签名一切正常。 但是将支付宝公钥转成PEM个时候，创建rsa公钥对象都失败。 

```lua

    --  pubkey是用支付宝工具生成的pkcs#1公钥转成PEM格式的公钥
    local pubkey = [[-----BEGIN RSA PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm9HI/Xedl1uKkzaZOTzW
CyAD3zojrXO6XLgmD+CGnwj/gYm2MaeEp1xw+5FKVfUoGF/J8rRzBOY4nslg7JsL
hO3Q8pqa94T942i4DauVgwY+ieDrGuaJ895QaCHHltu62XCVVyXRKmisbZteXJYr
NYyPetdVoaqjoXi+0jQPIvPzOz0y1JFGwvw+kTOvDrN8IlMCrJEpDI7QRlhLTRKV
tv1dRYC8hSjj2VkOVq4uEH+SUc9rvIRt44G6eHWIR1C1HiosjOiY/wT+kfVfkm+Y
qntaOmT9jy20y1A97ZCj9SuTEWGbx9pZvMcVwvh+z63Ds27hvnPssNHyDqjejsCx
hQIDAQAB
-----END RSA PUBLIC KEY-----]];

 local pub, err  = resty_rsa:new({ public_key = pubkey, algorithm = 'SHA256'});
    if not pub then
        return res:json {  msg = err };
    end
```

错误信息为：  "wrong tag: nested asn1 error: nested asn1 error: Field=n, Type=RSA: ASN1 lib"

**Comment by epiphyllum** [comment]
还有个问题是， 支付宝生成的密钥对(pkcs#1格式中， 公钥为什么比lua-resty-rsa生成的公钥要长？

**Comment by epiphyllum** [comment]
 ~/tmp/ openssl genrsa -out rsa_private_key.pem 2048

 ~/tmp/ openssl rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem

![image](https://user-images.githubusercontent.com/8348065/122336750-e4178c00-cf6f-11eb-9222-22d0aa2cfddc.png)

openssl生成的公私钥对， 我发现生成的公钥比lua-resty-rsa一下方法生成的公钥要长， 请问下是什么原因啊？
```lua
    local public_key, priv_key, err = resty_rsa:generate_rsa_keys(2048)
    if not public_key then
        ngx.say('generate rsa keys err: ', err)
        return ;
    end
```
感觉lua-resty-rsa生成的公钥， 比openssl生成的公钥要短。

**Comment by epiphyllum** [comment]
看起来， 支付宝工具生成的公私钥对， 和openssl工具生成的一样的。 
但是lua-resty-rsa生成的公私钥对中的公钥要短一下。

**Comment by epiphyllum** [comment]
openssl 生成的公钥长度是   64*6+8 = 392

```lua
 local public_key, priv_key, err = resty_rsa:generate_rsa_keys(2048)
    if not public_key then
        ngx.say('generate rsa keys err: ', err)
        return ;
    end
```
这段代码生成的公钥长度是:   64*5 + 40 = 360

**Comment by spacewander** [comment]
首先，需要明确下你用的 lua-resty-rsa 的版本哈。

说来话长，先从公私钥格式分类说起：

私钥分两类：
1. PKCS#1：RSA PRIVATE KEY 开头
2. PKCS#8：PRIVATE KEY 开头

公钥分两类：
1. PKCS#1：RSA PUBLIC KEY 开头
2. PKIX： PUBLIC KEY 开头 （我的库的文档错了，不存在 PKCS#8 的公钥，应该是 PKIX 才对）

可以看下 Go 标准库对应的文档：https://golang.org/pkg/crypto/x509/#ParsePKCS8PrivateKey

openssl rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem
生成的是 PKIX 格式的公钥，你可以看到它是 “PUBLIC KEY” 开头的。

相似的，openssl rsa -in rsa_private_key.pem -RSAPublicKey_out -out rsa_public_key.pem 生成的是
PKCS#1 格式的公钥。

generate_rsa_keys 默认生成的公钥是 PKCS#1 格式的，不过你可以通过 resty_rsa:generate_rsa_keys(2048, true) 来让它生成PKIX 格式的公钥。 

最后回到支付宝的问题。如果支付宝生成的公钥，和 `openssl rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem` 生成的公钥一样长，那么说明他们的格式是一样的。

这样有两个推论：
1. 在使用支付宝公钥时，应该采用跟 openssl 公钥一样的开头，也即 “-----BEGIN PUBLIC KEY”，而不是 “-----BEGIN RSA PUBLIC KEY”。
2. 虽然支付宝声称它的公钥是 PKCS#1 格式，但如果它跟 openssl 默认生成的公钥是同一个格式，那么它其实应该是 PKIX 格式的。
