### ISSUE TITLE
archlinux EVP_PKEY_size error

### ISSUE THREAD

**Issue by transtone** [spacewander/lua-resty-rsa#54]
```shell
2024/01/05 11:02:43 [error] 5776#0: *1 lua entry thread aborted: runtime error: 
/opt/openresty/site/lualib/resty/rsa.lua:388: 
/opt/openresty/luajit/lib/libluajit-5.1.so.2: undefined symbol: EVP_PKEY_size
```

**Comment by spacewander** [comment]
What OpenSSL version used in your system? Seems it doesn't export the method EVP_PKEY_size.

**Comment by Amitesh21** [comment]
Hey @spacewander, I am also seeing the same error. We were using the Openssl v1.1.1r with openresty v1.25.3.1 but seems like openssl 1.1.1 is deprecated now. I am trying to bump openssl to v3.2.1, are the new release changes not legacy compatible? Any sample or doc you can share to fix the issue? Thanks.

**Comment by spacewander** [comment]
According to https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_size.html, EVP_PKEY_size is renamed to EVP_PKEY_get_size. Would you give it a try?

**Comment by nogolang** [comment]
you should edit rsa.lua in /usr/local/openssl/lualib/resty/rsa.lua

```
int EVP_PKEY_size(EVP_PKEY *pkey);
--new version is updated EVP_PKEY_get_size，but you need keep old define
int EVP_PKEY_get_size(EVP_PKEY *pkey);
```

```
--update this code
--local size = C.EVP_PKEY_size(pkey)
local size = C.EVP_PKEY_get_size(pkey)
```
--then you can fix it

**Comment by spacewander** [comment]
@nogolang 
Would you submit a PR for this? Thanks!

**Comment by spacewander** [comment]
We can use pcall to check if the method is defined:
https://github.com/spacewander/lua-resty-rsa/blob/d4e22cfaa851eabbcc50029e20156ae236d733d8/lib/resty/rsa.lua#L151

**Comment by nogolang** [comment]
> @nogolang Would you submit a PR for this? Thanks!

ok,i try

**Comment by spacewander** [comment]
Fixed in https://github.com/spacewander/lua-resty-rsa/pull/55
