### ISSUE TITLE
您好，使用公钥新建对象失败，使用私钥新建对象是成功的，原因是什么呢？

### ISSUE THREAD

**Issue by pepeWaverF** [spacewander/lua-resty-rsa#9]
您好，首先感谢提供封装好的rsa库。

我的问题是，我现在使用私钥创建了签名。但是验签时，创建ras对象，一直报错： no start line.
但实际传入的公钥是有开头-----BEGIN PUBLIC KEY-----的。
我的私钥和公钥，不是用generate_rsa_keys生成，使用openssl genrsa 等命令生成的。

这点，不知道作者是否知道原因呢

**Comment by spacewander** [comment]
多谢您的赏识。

`-----BEGIN PRIVATE PUBLIC KEY-----` 开头的公钥是 pkcs#1 格式的密钥，也就是我们通常意义上的 RSA 密钥。
`-----BEGIN PUBLIC KEY-----` 开头的公钥是 pkcs#8 格式的密钥，除了包含密钥之外，它还包含了其他元数据。
可以参考这个回答：
http://stackoverflow.com/questions/20065304/what-is-the-differences-between-begin-rsa-private-key-and-begin-private-key

lua-resty-rsa 这个库，现在只支持 pkcs#1 ，您可以把 pkcs8 格式的公钥转化成 pkcs1 格式，再使用。

**Comment by spacewander** [comment]
多谢您的赏识。

`-----BEGIN PRIVATE PUBLIC KEY-----` 开头的公私钥是 pkcs#1 格式的密钥，也就是我们通常意义上的 RSA 密钥。
`-----BEGIN PUBLIC KEY-----` 开头的公私钥是 pkcs#8 格式的密钥，除了包含密钥之外，它还包含了其他元数据。
可以参考这个回答：
http://stackoverflow.com/questions/20065304/what-is-the-differences-between-begin-rsa-private-key-and-begin-private-key

lua-resty-rsa 这个库，现在只支持 pkcs#1 ，您可以把 pkcs8 格式的公钥转化成 pkcs1 格式，再使用。

**Comment by imlison** [comment]
@spacewander 能请教下怎么从pkcs8公钥转pkcs1吗？网上找到的资料都是转私钥的，不能转公钥。

**Comment by spacewander** [comment]
@imlison
http://stackoverflow.com/questions/18039401/how-can-i-transform-between-the-two-styles-of-public-key-format-one-begin-rsa/27930720#27930720

**Comment by spacewander** [comment]
最新版已经可以通过指定 `key_type` 来支持 pkcs#8 格式的公钥了。

```lua
-- creates a rsa object with pkcs#8 format of public key
local resty_rsa = require "resty.rsa"
local pub, err = resty_rsa:new({
    public_key = RSA_PKCS8_PUB_KEY,
    key_type = resty_rsa.KEY_TYPE.PKCS8,
})
```
